
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: webhook_hotmart_development
  username: 'postgres'
  password: 'postgres'
  host: localhost
  port: 5432

test:
  <<: *default
  database: webhook_hotmart_test
  username: 'postgres'
  password: 'postgres'
  host: localhost
  port: 5432

production:
  <<: *default
  database: webhook_hotmart_production
  username: webhook_hotmart
  password: <%= ENV['WEBHOOK_HOTMART_DATABASE_PASSWORD'] %>
